use std::fs;
use std::path::Path;

use anyhow::Context;
use anyhow::Result;
use redis;
use serde_json as json;

pub mod model;

const DATA_FILE: &'static str = "../parsed/cs_1723076144.json";
const REDIS_SERVER: &str = "redis://127.0.0.1:6379/";

fn restart_redis() -> Result<()> {
    Ok(())
}

struct State {
    conn: redis::Connection,
}

impl State {
    pub fn new(reset_rdb: bool) -> Result<Self> {
        if reset_rdb {
            restart_redis()?;
        }

        let client = redis::Client::open(REDIS_SERVER)?;
        let conn = client.get_connection()?;
        let mut s = State { conn };

        if reset_rdb {
            s.load_data(DATA_FILE)?;
            s.index()?;
        }

        Ok(s)
    }

    fn index(&mut self) -> Result<()> {
        redis::pipe()
            .cmd("FT.CREATE")
            .arg("idx:pubs")
            .arg("ON")
            .arg("JSON")
            .arg("PREFIX")
            .arg("1")
            .arg("pub:")
            .arg("SCHEMA")
            .arg("$.title")
            .arg("AS")
            .arg("title")
            .arg("TEXT")
            .arg("$.abstract")
            .arg("AS")
            .arg("abstract")
            .arg("TEXT")
            .query::<()>(&mut self.conn)?;
        Ok(())
    }

    /// Parse dataset from json file (generated by Python) and load into redis
    fn load_data(&mut self, data_file: impl AsRef<Path>) -> Result<()> {
        json::from_str::<Vec<model::Publication>>(&fs::read_to_string(data_file)?)?
            .iter()
            .map(|p| -> Result<String> { Ok(json::to_string(p)?) })
            .enumerate()
            .try_for_each(|(i, r)| -> Result<()> {
                Ok(redis::pipe()
                    .cmd("JSON.SET")
                    .arg(format!("pub:{i}"))
                    .arg("$")
                    .arg(r?)
                    .query(&mut self.conn)?)
            })
    }

    pub fn search(&mut self, query: &str) -> Result<Vec<model::Publication>> {
        Ok(redis::pipe()
            .cmd("FT.SEARCH")
            .arg("idx:pubs")
            .arg(format!("(%{query}%|{query}*)"))
            .query::<Vec<model::Publications>>(&mut self.conn)?
            .into_iter()
            .next()
            .context("failed to parse redis search response")?
            .inner())
    }
}

#[cfg(test)]
pub mod tests {
    use super::*;

    #[test]
    fn test_start() -> Result<()> {
        let mut state = State::new(false)?;

        let search_result = state.search("cache")?;
        assert!(search_result.len() > 0);

        let search_result = state.search("asdasdasd")?;
        assert!(search_result.len() == 0);

        Ok(())
    }
}
